In [2]:
import numpy as np

#### 속도 비교

In [4]:
def square_list0(N):
    squares=[]
    for n in range(N):
        squares=squares+[n**2]
    return squares

def square_list1(N):
    squares=[]
    for n in range(N):
        # 일반적으로 생성해서 더하는 방법
        squares += [n**2]
    return squares
        
def square_list2(N):
    squares=[]
    for n in range(N):
        # append라고 이미 정의된 메소드 이용하는 방법
        squares.append(n**2)
    return squares

def square_list3(N):
    # 동일한 방법이나 벡터연산으로 처리
    return [n**2 for n in range(N)]

def square_array(N):
    # Vectorize the entire operation
    #from numpy import arange # numpy에 있는 패키지 중 arange만 가져와서 사용
    #return arange(N)**2
    return np.arange(N)**2

n=100
print("Number:",n)
t1=time.time()
square_list0(n)
t2=time.time()
print("List0-Try:",t2-t1)

t1=time.time()
square_list1(n)
t2=time.time()
print("List1-Try:", t2-t1)

t1=time.time()
square_list2(n)
t2=time.time()
print("List2-Try:",t2-t1)

t1=time.time()
square_list3(n)
t2=time.time()
print("List3-Try",t2-t1)

Number: 100


NameError: name 'time' is not defined

### 색인

#### 기본적인 색인 : 파이썬의 리스트와 동일

In [5]:
# 색인
list1=[1,2,3,4,5,6]
arr1=np.array(list1)
print(list1)
print(arr1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [8]:
# 정수 인덱스로 리스트와 1차원 numpy 배열 접근 --> 참고) 원본은 변경되지 않음
print(list1[0])
print(arr1[0])
print("\n")
print(list1[1:3])
print(arr1[1:3])
print("\n")
print(list1[3:])
print(arr1[3:])
print("\n")
print(list1[:])
print(arr1[:])

1
1


[2, 3]
[2 3]


[4, 5, 6]
[4 5 6]


[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


#### 연습문제

In [9]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

In [11]:
np.arange(0,51,10)[:,np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [14]:
a=np.arange(0,51,10)[:,np.newaxis]+[0,1,2,3,4,5] # np.arange(0:6:1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [15]:
a[0][1]

1

In [16]:
a[0,2]

2

In [17]:
a[0:2,1]

array([ 1, 11])

In [18]:
a[0:6,2]

array([ 2, 12, 22, 32, 42, 52])

In [19]:
a[0,3:5]

array([3, 4])

In [27]:
a[2:5:2,0:5:2]

array([[20, 22, 24],
       [40, 42, 44]])

In [28]:
a[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [29]:
# Boolean indexing
arr1=np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


#### 자료 만들기

In [48]:
# names - 학생이름, data - 국어/영어/수학/과학 성적이라고 생각하면 됨
names=np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
# 참고) numpy.random.randint(low,high=None,size=None,dtype='l')
data=np.random.randint(low=30,high=100,size=(7,4))
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[60 70 94 45]
 [37 57 85 30]
 [55 78 52 74]
 [87 83 99 94]
 [71 34 79 64]
 [96 92 53 41]
 [99 79 31 73]]


#### 이름이 Bob인 사람들만 찾기

In [31]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [33]:
print(names[names=="Bob"])
print(len(names[names=="Bob"]))

['Bob' 'Bob']
2


#### 이름이 Bob인 사람들의 성적 조회

In [34]:
data[names=="Bob"]

array([[81, 42, 52, 64],
       [76, 64, 98, 37]])

#### Bob이 2명이 있는데 이 중에서 전과목이 아니라 수학/과학의 성적만 보고싶을 때

In [35]:
data[names=="Bob",2:]

array([[52, 64],
       [98, 37]])

#### Bob이 2명 있는데 처음 나온 Bob의 성적만 보고싶을 때

In [36]:
data[names=="Bob"][0]

array([81, 42, 52, 64])

#### 이름이 Bob,Will인 사람들의 성적

In [43]:
data[(names=="Bob") | (names=="Will")]

array([[81, 42, 52, 64],
       [87, 75, 41, 30],
       [76, 64, 98, 37],
       [79, 31, 96, 74]])

In [49]:
# step1)
print(data)
data[data<=70]=0
data[data>70]=1
print(data)

[[60 70 94 45]
 [37 57 85 30]
 [55 78 52 74]
 [87 83 99 94]
 [71 34 79 64]
 [96 92 53 41]
 [99 79 31 73]]
[[0 0 1 0]
 [0 0 1 0]
 [0 1 0 1]
 [1 1 1 1]
 [1 0 1 0]
 [1 1 0 0]
 [1 1 0 1]]


In [50]:
# step2)
# 참고) 원하는 값을 찾을 때는 np.where을 사용
# 1로 패스한 사람들의 데이터만 찾음 -> 결과가 어떠한 것을 의미하는지 잘 확인할 것
np.where(data>0)

(array([0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 6], dtype=int64),
 array([2, 2, 1, 3, 0, 1, 2, 3, 0, 2, 0, 1, 0, 1, 3], dtype=int64))

In [51]:
# step3/4)
# 이를 바탕으로 이름에 대한 유니크한 index를 찾아서 누가 패스했는지 찾아보자
print(np.unique(np.where(data>0)[0]))
print(names[np.unique(np.where(data>0)[0])])

[0 1 2 3 4 5 6]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
