### 모양 변경 : shape를 바꾸자 -> reshape

In [5]:
import numpy as np

In [6]:
# Numpy Transform
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
arr=arr.reshape((4,8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [9]:
arr=arr.reshape((3,9))

ValueError: cannot reshape array of size 32 into shape (3,9)

In [10]:
# Transpose
arr=arr.reshape((4,8))
print(arr)
print(arr.T)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  8 16 24]
 [ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]]


### 기본적인 수학 함수들

In [12]:
arr1=np.arange(10)
print(arr1)
print(np.sqrt(arr1))

arr2=np.arange(30,40,1)
print(arr2)

print(np.maximum(arr1,arr2))

print(arr1.max())
print(arr2.max())

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[30 31 32 33 34 35 36 37 38 39]
[30 31 32 33 34 35 36 37 38 39]
9
39


In [13]:
# pandas 사용 준비
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

##### 예제로 사용할 데이터 만들기 
###### 만들 데이터 :  주가 가격에 대한 것이며, 여러 날짜에 대한 가격이니 파이썬 기본 형인 리스트를 기본으로 형성할 수 있음. 본인이 사용할 주식의 종가라 생각하고 5일 정도의 주가의 가격을 샘플로 만드시오

In [16]:
stock_price_list=[10000,10300,9900,10500,11000]
stock_price_Series=pd.Series([10000,10300,9900,10500,11000])
print(stock_price_list)
print(stock_price_Series)

[10000, 10300, 9900, 10500, 11000]
0    10000
1    10300
2     9900
3    10500
4    11000
dtype: int64


In [17]:
# 리스트로 첫번째 원소 값 접근
stock_price_list[0]

10000

In [18]:
# 시리즈로 첫번째 원소 값 접근
stock_price_Series[0]

10000

#### index 만들기

In [19]:
stock_price_Series_withIndex=pd.Series([10000,10300,9900,10500,11000],
                             index=["2019-03-01","2019-03-02","2019-03-03","2019-03-04","2019-03-05"])
stock_price_Series_withIndex

2019-03-01    10000
2019-03-02    10300
2019-03-03     9900
2019-03-04    10500
2019-03-05    11000
dtype: int64

In [20]:
stock_price_Series_withIndex["2019-03-01"]

10000

In [23]:
stock_price_Series_withIndex.values

array([10000, 10300,  9900, 10500, 11000], dtype=int64)

#### stock_price_Series_withIndex의 index, values 출력

In [35]:
for i in range(0,len(stock_price_Series_withIndex)):
    print(stock_price_Series_withIndex.index[i])
    print(stock_price_Series_withIndex.values[i])

2019-03-01
10000
2019-03-02
10300
2019-03-03
9900
2019-03-04
10500
2019-03-05
11000


In [29]:
for idx,value in enumerate(stock_price_Series_withIndex):
    print(idx)
    print(value)

0
10000
1
10300
2
9900
3
10500
4
11000


In [36]:
for i in stock_price_Series_withIndex.index:
    print(i)
    print(stock_price_Series_withIndex[i])

2019-03-01
10000
2019-03-02
10300
2019-03-03
9900
2019-03-04
10500
2019-03-05
11000


In [38]:
# 정수 인덱스에 '여러개'&'규칙'으로 인한 슬라이싱이 아니라 내가 원하는 특정한 것을 가져올 경우
stock_price_Series_withIndex[[1,2,4]]

2019-03-02    10300
2019-03-03     9900
2019-03-05    11000
dtype: int64

In [39]:
# 여러개 & 규칙으로 가능(슬라이싱) 
stock_price_list[0:3]

[10000, 10300, 9900]

In [41]:
# 규칙이 아니라 내가 원하는 임의의 것을 여러 개인 경우에는 에러 발생
stock_price_list[[0,3]] 

TypeError: list indices must be integers or slices, not list

In [43]:
# sol) Use List and for loop => numpy에서 속도 비교할 때 사용한 방법 이용
# tip) 리스트 안에 for문을 이용해서 리스트 안의 특정 원소 생성
# tip) for문의 기본은 리스트의 값을 모두 접근하는 것
search_index=[0,3]
[stock_price_list[i] for i in search_index]

[10000, 10500]

### Series의 다양한 기능
#### 모든 원소 일괄 적용
##### 간단히 표현

In [44]:
# 01) 모든 원소에 일괄 적용
# Series - 다양한 기능 - value 관련
stock_price_Series_withIndex*2

2019-03-01    20000
2019-03-02    20600
2019-03-03    19800
2019-03-04    21000
2019-03-05    22000
dtype: int64

#### Boolean indexing을 활용한 조건 검색

In [46]:
stock_price_Series_withIndex[stock_price_Series_withIndex>10500]

2019-03-05    11000
dtype: int64

#### index 관련한 사항 :  많이 있을 때 원하는 인덱스가 있는지 없는지

In [47]:
# Series - 다양한 기능 - index 관련
print("2019-03-02" in stock_price_Series_withIndex)

True


In [48]:
# in 이라는 것에 비교 대상이 index가 아니라 value인 경우에는?
11000 in stock_price_Series_withIndex

False

In [49]:
# index와 다른 값으로 비교해서 확인해보자
"2019-03-05" in stock_price_Series_withIndex

True

In [50]:
# 참고)파이썬의 기본 구조 dict와 상당히 유사한데, 어떻게 상호 변환을 하는지 관련 부분
# Series/Pandas가 기본적으로 index+value 구조인데, 이는 파이선의 기본 자료형인 dict와 상당히 유사
# 이를 통해서 서로 어떻게 변환을 할 수 있는지 알아보자

In [51]:
# Series-index
sdata={"app" : 1000, "ms" : 2000, "amazon" : 3000}
obj3=pd.Series(sdata)
obj3

app       1000
ms        2000
amazon    3000
dtype: int64

In [52]:
states=["google","app","amazon"]
obj4=pd.Series(sdata,states) # index중심으로 setting
obj4

google       NaN
app       1000.0
amazon    3000.0
dtype: float64

In [57]:
print(obj3)
print("-------")
print(obj4)

app       1000
ms        2000
amazon    3000
dtype: int64
-------
google       NaN
app       1000.0
amazon    3000.0
dtype: float64


In [58]:
print(obj3+obj4)
print(obj3-obj4)

amazon    6000.0
app       2000.0
google       NaN
ms           NaN
dtype: float64
amazon    0.0
app       0.0
google    NaN
ms        NaN
dtype: float64


#### 실제 접근하는 메서드를 이용해서 접근 : at/iat

In [62]:
print(stock_price_Series_withIndex.at["2019-03-01"])
print(stock_price_Series_withIndex.iat[0])

10000
10000


#### 실제 접근하는 메서드를 이용해서 접근 : loc/iloc

In [64]:
# 범위 지정
print(stock_price_Series_withIndex.loc["2019-03-01":"2019-03-02"])
# 특정한 것만 리스트로 선택
print(stock_price_Series_withIndex.loc[["2019-03-01","2019-03-03"]])

2019-03-01    10000
2019-03-02    10300
dtype: int64
2019-03-01    10000
2019-03-03     9900
dtype: int64


In [66]:
print(stock_price_Series_withIndex.iloc[0:3])
print(stock_price_Series_withIndex.iloc[[0,2]])

2019-03-01    10000
2019-03-02    10300
2019-03-03     9900
dtype: int64
2019-03-01    10000
2019-03-03     9900
dtype: int64


In [67]:
add_data=Series([12345],index=["2019-03-07"])
print(stock_price_Series_withIndex.append(add_data))
print(stock_price_Series_withIndex)

2019-03-01    10000
2019-03-02    10300
2019-03-03     9900
2019-03-04    10500
2019-03-05    11000
2019-03-07    12345
dtype: int64
2019-03-01    10000
2019-03-02    10300
2019-03-03     9900
2019-03-04    10500
2019-03-05    11000
dtype: int64


In [68]:
# append할 때 중복된 경우에 안 들어가게 하려면?
add_data=Series([12345],index=["2019-03-05"])
print(stock_price_Series_withIndex.append(add_data, verify_integrity=True))
print(stock_price_Series_withIndex) 

ValueError: Indexes have overlapping values: Index(['2019-03-05'], dtype='object')

#### 자료만 입력 & 컬럼 이름 추가

In [91]:
d=[0,1,2,3,4]
df=pd.DataFrame(d) # 열에 대해 index 부여
print(df)
#ds=pd.Series(d)
#print(ds)

   0
0  0
1  1
2  2
3  3
4  4


In [92]:
df.columns=["column1"]
print(df)

   column1
0        0
1        1
2        2
3        3
4        4


#### 컬럼 추가하면서 데이터 입력

In [93]:
df["newCol1"]=d
print(df)
df["newCol2"]=5
print(df)

   column1  newCol1
0        0        0
1        1        1
2        2        2
3        3        3
4        4        4
   column1  newCol1  newCol2
0        0        0        5
1        1        1        5
2        2        2        5
3        3        3        5
4        4        4        5


##### df에서 newCol3을 기존의 newCol2의 값을 기준으로 만들고, 기존의 newCol2의 모든 값을 100배한 값을 newCol3에 생성

In [94]:
df["newCol3"]=df.newCol2*100
df

column1  newCol1  newCol2  newCol3
0        0        0        5      500
1        1        1        5      500
2        2        2        5      500
3        3        3        5      500
4        4        4        5      500

##### df에서 newCol2에서 2번째 값을 확인하고 이 값을 2000으로 변경

In [96]:
df.newCol2[1]=2000
df

column1  newCol1  newCol2  newCol3
0        0        0        5      500
1        1        1     2000      500
2        2        2        5      500
3        3        3        5      500
4        4        4        5      500

In [97]:
print(df.iloc[1,2])

2000


#### 컬럼 제거하기 : 여러가지 방법 존재

##### 방법1) del 함수 이용

In [98]:
print(df)
del df["column1"]
print(df)

   column1  newCol1  newCol2  newCol3
0        0        0        5      500
1        1        1     2000      500
2        2        2        5      500
3        3        3        5      500
4        4        4        5      500
   newCol1  newCol2  newCol3
0        0        5      500
1        1     2000      500
2        2        5      500
3        3        5      500
4        4        5      500


##### 방법2) 필요한 컬럼 선택으로 간접 제거

In [99]:
print(df.columns.values)
newColList=['newCol2','newCol3']
df[newColList] # df자체가 바뀌는 것은 아님

['newCol1' 'newCol2' 'newCol3']


newCol2  newCol3
0        5      500
1     2000      500
2        5      500
3        5      500
4        5      500

##### 방법3) drop 이용

In [103]:
print(df.drop("newCol2",axis=1)) # axis=1 열 중심으로 제거
print(df.drop(3,axis=0)) # 행 중심으로 3에 해당하는 index 제거

   newCol1  newCol3
0        0      500
1        1      500
2        2      500
3        3      500
4        4      500
   newCol1  newCol2  newCol3
0        0        5      500
1        1     2000      500
2        2        5      500
4        4        5      500


#### DF에서 index 이름 만들기

In [104]:
df.index.name="count"
df

newCol1  newCol2  newCol3
count                           
0            0        5      500
1            1     2000      500
2            2        5      500
3            3        5      500
4            4        5      500

In [128]:
stock_price_Df_withIndex=pd.DataFrame([1000,10350,10100,9600,10500,11350],
                                     index=["2019-03-01","2019-03-02","2019-03-03","2019-03-04","2019-03-05","2019-03-06"])

stock_price_Df_withIndex

0
2019-03-01   1000
2019-03-02  10350
2019-03-03  10100
2019-03-04   9600
2019-03-05  10500
2019-03-06  11350

In [129]:
stock_price_Df_withIndex.rename(columns={"0":"시가"},inplace=True)
stock_price_Df_withIndex

0
2019-03-01   1000
2019-03-02  10350
2019-03-03  10100
2019-03-04   9600
2019-03-05  10500
2019-03-06  11350

In [130]:
stock_price_Df_withIndex.rename(columns={0:"시가"},inplace=True)
stock_price_Df_withIndex

시가
2019-03-01   1000
2019-03-02  10350
2019-03-03  10100
2019-03-04   9600
2019-03-05  10500
2019-03-06  11350

In [131]:
stock_price_Df_withIndex.rename(columns={1:"종가"},inplace=True)
stock_price_Df_withIndex

시가
2019-03-01   1000
2019-03-02  10350
2019-03-03  10100
2019-03-04   9600
2019-03-05  10500
2019-03-06  11350

In [133]:
stock_price_Df_withIndex["종가"]=stock_price_Df_withIndex
stock_price_Df_withIndex["고가"]=[1500,200,3000,4000,5000,3040]
stock_price_Df_withIndex["저가"]=stock_price_Df_withIndex["고가"]
stock_price_Df_withIndex

시가     종가    고가    저가
2019-03-01   1000   1000  1500  1500
2019-03-02  10350  10350   200   200
2019-03-03  10100  10100  3000  3000
2019-03-04   9600   9600  4000  4000
2019-03-05  10500  10500  5000  5000
2019-03-06  11350  11350  3040  3040

In [134]:
# stock_price_Df_withIndex.iat[0] -> 에러 발생 : 두 개의 위치값이 필요
stock_price_Df_withIndex.iat[0,0]

1000

In [141]:
# 앞의 데이터에서 2019년 3월 1일의 시가/종가는?
print(stock_price_Df_withIndex.loc["2019-03-01",["시가","종가"]])

시가    1000
종가    1000
Name: 2019-03-01, dtype: int64


In [142]:
# 앞의 데이터에서 2019년 3월 1일 ~ 2019년 3월 3일 사이의 시가/종가/고가/저가는?
print(stock_price_Df_withIndex.loc["2019-03-01":"2019-03-03","시가":"저가"])

               시가     종가    고가    저가
2019-03-01   1000   1000  1500  1500
2019-03-02  10350  10350   200   200
2019-03-03  10100  10100  3000  3000


In [145]:
stock_price_Df_withIndex.T

2019-03-01  2019-03-02  2019-03-03  2019-03-04  2019-03-05  2019-03-06
시가        1000       10350       10100        9600       10500       11350
종가        1000       10350       10100        9600       10500       11350
고가        1500         200        3000        4000        5000        3040
저가        1500         200        3000        4000        5000        3040

In [143]:
stock_price_Df_withIndex.values

array([[ 1000,  1000,  1500,  1500],
       [10350, 10350,   200,   200],
       [10100, 10100,  3000,  3000],
       [ 9600,  9600,  4000,  4000],
       [10500, 10500,  5000,  5000],
       [11350, 11350,  3040,  3040]], dtype=int64)

In [144]:
stock_price_Df_withIndex.shape

(6, 4)

In [146]:
stock_price_Df_withIndex.shape[0]

6

In [147]:
stock_price_Df_withIndex.shape[1]

4

In [148]:
stock_price_Df_withIndex.size

24

In [149]:
stock_price_Df_withIndex.ndim

2

#### DF : reindex

In [151]:
obj=pd.Series([4.5,7.2,-5.3],index=["c","b","a"])
obj

c    4.5
b    7.2
a   -5.3
dtype: float64

In [152]:
obj2 = obj.reindex(["a","b","c","d","e"])
obj2

a   -5.3
b    7.2
c    4.5
d    NaN
e    NaN
dtype: float64

In [153]:
obj.reindex(["a","b"])

a   -5.3
b    7.2
dtype: float64

In [155]:
obj.reindex(["a","b","c","d","e"],fill_value=0)

a   -5.3
b    7.2
c    4.5
d    0.0
e    0.0
dtype: float64

#### 실질적으로 "보간법"으로 처리하는 경우도 많음

In [156]:
# 보간법
obj=pd.Series([4.5,7.2,-5.3], index=["a","b","c"])
print(obj)
print("-------")
print(obj.reindex(["a","d","e","c","b"]))
print("-------")
print(obj.reindex(["a","d","e","c","b"]).interpolate())

a    4.5
b    7.2
c   -5.3
dtype: float64
-------
a    4.5
d    NaN
e    NaN
c   -5.3
b    7.2
dtype: float64
-------
a    4.500000
d    1.233333
e   -2.033333
c   -5.300000
b    7.200000
dtype: float64


In [ ]:
# 앞의 데이터를 가지고 Series가 아닌 DataFrame으로 만들고 나서, reindex는 앞에서와 같이 "a","d","e","c","b"로 하고, reindex한 결과 보이기
# "interPo"라는 새로운 컬럼을 만들어서 interpolate를 한 값으로 채우기

In [160]:
obj=pd.DataFrame([4.5,7.2,-5.3],index=["c","b","a"])
obj=obj.reindex(["a","d","e","c","b"])
print(obj)
print("-----------------------")
obj["interPo"] = obj.iloc[:,0].interpolate()
print(obj)

     0
a -5.3
d  NaN
e  NaN
c  4.5
b  7.2
-----------------------
     0   interPo
a -5.3 -5.300000
d  NaN -2.033333
e  NaN  1.233333
c  4.5  4.500000
b  7.2  7.200000
